{
 "title": "연속 불량 감시",
 "tags": [ "설비 불량 현황" ],
 "time": { "from": "now/d", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "DATABASE", "label": "분사/지점 선택", "query": "influxdb" },
   {
    "name": "FACILITY",
    "label": "검사기",
    "query": "show tag values from /inspection/ with key=facility"
   },
   {
    "name": "CHANNEL",
    "label": "채널",
    "query": "show tag values from /inspection/ with key=channel"
   }
  ]
 },
 "panels": [
  {
   "title": "설비 연속불량 검출 알림",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "locale", "label": "분당 검출수" }
   ],
   "targets": [
    {
     "alias": "$col($tag_facility:$tag_channel )",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "facility" ], "type": "tag" },
      { "params": [ "channel" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/alram.continuous.failures.detail-*/",
     "select": [
      [
       { "params": [ "cpk" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "COUNT" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "facility", "operator": "=~", "value": "/^$FACILITY$/" },
      { "condition": "AND", "key": "channel", "operator": "=~", "value": "/^$CHANNEL$/" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "/alram.continuous.failures.detail-*/",
     "select": [
      [
       { "params": [ "cpk" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       },
       { "params": [ "CUML" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "facility", "operator": "=~", "value": "/^$FACILITY$/" },
      { "condition": "AND", "key": "channel", "operator": "=~", "value": "/^$CHANNEL$/" }
     ]
    }
   ]
  },
  { "title": "알람 목록", "type": "alertlist", "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 } },
  { "title": "검사기별 연속불량", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "$FACILITY",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "repeat": "FACILITY",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "CNT",
     "measurement": "/^alram.continuous.failures.detail-*/",
     "select": [
      [
       { "params": [ "cpk" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "facility", "operator": "=~", "value": "/^$FACILITY$/" }
     ]
    }
   ]
  },
  {
   "title": "$FACILITY",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "CNT",
     "measurement": "/^alram.continuous.failures.detail-*/",
     "select": [
      [
       { "params": [ "cpk" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "facility", "operator": "=~", "value": "/^$FACILITY$/" }
     ]
    }
   ]
  },
  {
   "title": "$FACILITY",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "CNT",
     "measurement": "/^alram.continuous.failures.detail-*/",
     "select": [
      [
       { "params": [ "cpk" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "facility", "operator": "=~", "value": "/^$FACILITY$/" }
     ]
    }
   ]
  },
  {
   "title": "검사기별 연속 불량 검출 상세 내역",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "검사기 ($FACILITY : $CHANNEL)에서의 연속불량 검출 이력",
     "type": "table",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 14 },
     "repeat": "FACILITY",
     "targets": [
      {
       "alias": "$col",
       "measurement": "/^alram.continuous.failures.detail-*/",
       "query": "SELECT \"inm\", \"iid\", \"facility\", \"channel\", \"model\", \"tuid\", \"min\", \"max\", \"val\" FROM /^alram*/ WHERE $timeFilter",
       "select": [
        [
         { "params": [ "inm" ], "type": "field" }
        ],
        [
         { "params": [ "iid" ], "type": "field" }
        ],
        [
         { "params": [ "facility" ], "type": "field" }
        ],
        [
         { "params": [ "channel" ], "type": "field" }
        ],
        [
         { "params": [ "model" ], "type": "field" }
        ],
        [
         { "params": [ "tuid" ], "type": "field" }
        ],
        [
         { "params": [ "min" ], "type": "field" }
        ],
        [
         { "params": [ "max" ], "type": "field" }
        ],
        [
         { "params": [ "val" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "facility", "operator": "=~", "value": "/^$FACILITY$/" },
        { "condition": "AND", "key": "channel", "operator": "=~", "value": "/^$CHANNEL$/" }
       ]
      }
     ]
    },
    {
     "title": "검사기 ($FACILITY : $CHANNEL)에서의 연속불량 검출 이력",
     "type": "table",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 14 },
     "targets": [
      {
       "alias": "$col",
       "measurement": "/^alram.continuous.failures.detail-*/",
       "query": "SELECT \"inm\", \"iid\", \"facility\", \"channel\", \"model\", \"tuid\", \"min\", \"max\", \"val\" FROM /^alram*/ WHERE $timeFilter",
       "select": [
        [
         { "params": [ "inm" ], "type": "field" }
        ],
        [
         { "params": [ "iid" ], "type": "field" }
        ],
        [
         { "params": [ "facility" ], "type": "field" }
        ],
        [
         { "params": [ "channel" ], "type": "field" }
        ],
        [
         { "params": [ "model" ], "type": "field" }
        ],
        [
         { "params": [ "tuid" ], "type": "field" }
        ],
        [
         { "params": [ "min" ], "type": "field" }
        ],
        [
         { "params": [ "max" ], "type": "field" }
        ],
        [
         { "params": [ "val" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "facility", "operator": "=~", "value": "/^$FACILITY$/" },
        { "condition": "AND", "key": "channel", "operator": "=~", "value": "/^$CHANNEL$/" }
       ]
      }
     ]
    },
    {
     "title": "검사기 ($FACILITY : $CHANNEL)에서의 연속불량 검출 이력",
     "type": "table",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 14 },
     "targets": [
      {
       "alias": "$col",
       "measurement": "/^alram.continuous.failures.detail-*/",
       "query": "SELECT \"inm\", \"iid\", \"facility\", \"channel\", \"model\", \"tuid\", \"min\", \"max\", \"val\" FROM /^alram*/ WHERE $timeFilter",
       "select": [
        [
         { "params": [ "inm" ], "type": "field" }
        ],
        [
         { "params": [ "iid" ], "type": "field" }
        ],
        [
         { "params": [ "facility" ], "type": "field" }
        ],
        [
         { "params": [ "channel" ], "type": "field" }
        ],
        [
         { "params": [ "model" ], "type": "field" }
        ],
        [
         { "params": [ "tuid" ], "type": "field" }
        ],
        [
         { "params": [ "min" ], "type": "field" }
        ],
        [
         { "params": [ "max" ], "type": "field" }
        ],
        [
         { "params": [ "val" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "facility", "operator": "=~", "value": "/^$FACILITY$/" },
        { "condition": "AND", "key": "channel", "operator": "=~", "value": "/^$CHANNEL$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "알람",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "(알람) 연속불량 검출 수",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "COUNT",
       "groupBy": [
        { "params": [ "10m" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "/^alram.continuous.failures.detail-*/",
       "select": [
        [
         { "params": [ "cpk" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         },
         {
          "params": [],
          "type": "cumulative_sum"
         },
         { "params": [ "A" ], "type": "alias" }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}