{
 "title": "CPK 현황",
 "tags": [ "CPK 현황" ],
 "time": { "from": "2018-07-04T09:54:12.423Z", "to": "2018-07-04T14:59:59.999Z" },
 "templating": {
  "list": [
   {
    "name": "INSPPROP_NAME",
    "label": "검사항목",
    "query": "SELECT NAME FROM t_inspection_property WHERE IDX <> 0;"
   },
   {
    "name": "MODEL",
    "label": "모델",
    "query": "show tag values from /inspection/ with key=model"
   },
   {
    "name": "INSPPROP",
    "label": "검사항목ID",
    "query": "SELECT IDX FROM t_inspection_property WHERE NAME IN (\"$INSPPROP_NAME\")"
   },
   {
    "name": "FACILITY",
    "label": "검사기",
    "query": "show tag values from /inspection/ with key=facility"
   },
   {
    "name": "CHANNEL",
    "label": "채널",
    "query": "show tag values from /inspection/ with key=channel"
   },
   {
    "name": "INTERVAL",
    "label": "집계단위",
    "query": "1s,3s,5s, 10s, 30s, 1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "DATABASE", "label": "본사/지점 선택", "query": "influxdb" }
  ]
 },
 "panels": [
  { "type": "singlestat", "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 }, "format": "none", "valueName": "avg" },
  {
   "title": "CPK for MODEL($MODEL) TESTED AT ($FACILITY CHANNEL $CHANNEL)",
   "type": "rms-plugin-app-cpk-01",
   "gridPos": { "h": 9, "w": 10, "x": 6, "y": 0 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "/^inspection.detail-*/",
     "query": "SELECT last(\"cpk\") AS \"cpk\", last(\"lsl\") AS \"lsl\", last(\"usl\") AS \"usl\", (last(\"usl\") + last(\"lsl\")) / 2 AS \"mean\" FROM /^inspection.detail-*/ WHERE (\"facility\" =~ /^$FACILITY$/ AND \"channel\" =~ /^$CHANNEL$/ AND \"iid\" =~ /^$INSPPROP$/ AND \"model\" =~ /^$MODEL$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "cpk" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "cpk" ], "type": "alias" }
      ],
      [
       { "params": [ "lsl" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "lsl" ], "type": "alias" }
      ],
      [
       { "params": [ "usl" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "usl" ], "type": "alias" }
      ],
      [
       { "params": [ "cp" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "cp" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "facility", "operator": "=~", "value": "/^$FACILITY$/" },
      { "condition": "AND", "key": "channel", "operator": "=~", "value": "/^$CHANNEL$/" },
      { "condition": "AND", "key": "iid", "operator": "=~", "value": "/^$INSPPROP$/" },
      { "condition": "AND", "key": "model", "operator": "=~", "value": "/^$MODEL$/" }
     ]
    },
    {
     "alias": "$col",
     "measurement": "/^inspection.detail-*/",
     "query": "SELECT mean(\"val\") AS \"val\" FROM /^inspection.detail-*/ WHERE (\"model\" =~ /^$MODEL$/ AND \"facility\" =~ /^$FACILITY$/ AND \"channel\" =~ /^$CHANNEL$/ AND \"iid\" =~ /^$INSPPROP_ID$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       { "params": [ "val" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "facility", "operator": "=~", "value": "/^$FACILITY$/" },
      { "condition": "AND", "key": "channel", "operator": "=~", "value": "/^$CHANNEL$/" },
      { "condition": "AND", "key": "iid", "operator": "=~", "value": "/^$INSPPROP$/" },
      { "condition": "AND", "key": "model", "operator": "=~", "value": "/^$MODEL$/" }
     ]
    }
   ]
  },
  {
   "title": "CPK 변동량",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "CPK 변동량" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "15m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "inspection.detail-20180101",
     "select": [
      [
       { "params": [ "cpk" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "CPK" ], "type": "alias" }
      ],
      [
       { "params": [ "cpk" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       },
       { "params": [ "DIFF" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latest CPK for $INSPPROP_NAME",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$col",
     "measurement": "inspection.detail-20180101",
     "select": [
      [
       { "params": [ "cpk" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "측정값 분포도",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "measurement": "/^inspection.detail-*/",
     "query": "SELECT mean(\"val\") AS \"val\" FROM /^inspection.detail-*/ WHERE (\"model\" =~ /^$MODEL$/ AND \"facility\" =~ /^$FACILITY$/ AND \"channel\" =~ /^$CHANNEL$/ AND \"iid\" =~ /^$INSPPROP_ID$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "model", "operator": "=~", "value": "/^$MODEL$/" },
      { "condition": "AND", "key": "iid", "operator": "=~", "value": "/^$INSPPROP$/" },
      { "condition": "AND", "key": "facility", "operator": "=~", "value": "/^$FACILITY$/" },
      { "condition": "AND", "key": "channel", "operator": "=~", "value": "/^$CHANNEL$/" }
     ]
    }
   ]
  },
  {
   "title": "Xbar Chart",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$INTERVAL" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^inspection.detail-*/",
     "query": "SELECT mean(\"IR2\") AS \"xbar\" FROM \"tblTrend-2018.01\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "xbar" ], "type": "alias" }
      ],
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "rmax" ], "type": "alias" }
      ],
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "rmin" ], "type": "alias" }
      ],
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "iid", "operator": "=~", "value": "/^$INSPPROP$/" },
      { "condition": "AND", "key": "facility", "operator": "=~", "value": "/^$FACILITY$/" },
      { "condition": "AND", "key": "channel", "operator": "=~", "value": "/^$CHANNEL$/" },
      { "condition": "AND", "key": "model", "operator": "=~", "value": "/^$MODEL$/" }
     ]
    }
   ]
  },
  {
   "title": "R Chart",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$INTERVAL" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^inspection.detail-*/",
     "select": [
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "rmax" ], "type": "alias" }
      ],
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ "rmin" ], "type": "alias" }
      ],
      [
       { "params": [ "val" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "count" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "iid", "operator": "=~", "value": "/^$INSPPROP$/" },
      { "condition": "AND", "key": "facility", "operator": "=~", "value": "/^$FACILITY$/" },
      { "condition": "AND", "key": "channel", "operator": "=~", "value": "/^$CHANNEL$/" },
      { "condition": "AND", "key": "model", "operator": "=~", "value": "/^$MODEL$/" }
     ]
    }
   ]
  }
 ]
}