{
 "title": "모델별 검사기록",
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "MODEL",
    "label": "모델",
    "query": "show tag values from /inspection/ with key=model"
   },
   {
    "name": "FACILITY",
    "label": "검사기",
    "query": "show tag values from /inspection/ with key=facility"
   },
   {
    "name": "CHANNEL",
    "label": "채널",
    "query": "show tag values from /inspection/ with key=channel"
   },
   {
    "name": "INTERVAL",
    "label": "집계단위",
    "query": "1s, 10s, 30s, 1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "aMAX", "label": "최대지정", "query": "10,50,100,500,1000,10000" },
   { "name": "aMIN", "label": "최소지정", "query": "100,50,10,5,0" }
  ]
 },
 "panels": [
  {
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "alias": "정상",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inspection",
     "query": "SELECT count(\"ok\") FROM \"inspection\" WHERE (\"model\" =~ /^$MODEL$/ AND \"facility\" =~ /^$FACILITY$/ AND \"channel\" =~ /^$CHANNEL$/ AND \"pass\" = 'true') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "불량",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"ok\") FROM \"inspection\" WHERE (\"model\" =~ /^$MODEL$/ AND \"facility\" =~ /^$FACILITY$/ AND \"channel\" =~ /^$CHANNEL$/ AND \"pass\" = 'false') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "alias": "$col",
     "measurement": "inspection",
     "select": [
      [
       { "params": [ "ok" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "model", "operator": "=~", "value": "/^$MODEL$/" },
      { "condition": "AND", "key": "facility", "operator": "=~", "value": "/^$FACILITY$/" },
      { "condition": "AND", "key": "channel", "operator": "=~", "value": "/^$CHANNEL$/" }
     ]
    }
   ]
  },
  {
   "title": "$INTERVAL 당 불량/양품 추이",
   "type": "graph",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "locale", "label": "판정수량" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$INTERVAL" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "inspection",
     "select": [
      [
       { "params": [ "ok" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "불량수" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "model", "operator": "=~", "value": "/^$MODEL$/" },
      { "condition": "AND", "key": "facility", "operator": "=~", "value": "/^$FACILITY$/" },
      { "condition": "AND", "key": "channel", "operator": "=~", "value": "/^$CHANNEL$/" },
      { "condition": "AND", "key": "pass", "operator": "=", "value": "false" }
     ]
    },
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$INTERVAL" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "inspection",
     "select": [
      [
       { "params": [ "ok" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "양품수" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "model", "operator": "=~", "value": "/^$MODEL$/" },
      { "condition": "AND", "key": "facility", "operator": "=~", "value": "/^$FACILITY$/" },
      { "condition": "AND", "key": "channel", "operator": "=~", "value": "/^$CHANNEL$/" },
      { "condition": "AND", "key": "pass", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 3 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "alias": "$col",
     "measurement": "inspection",
     "query": "SELECT count(\"ok\") FROM \"inspection\" WHERE (\"model\" =~ /^$MODEL$/ AND \"facility\" =~ /^$FACILITY$/ AND \"channel\" =~ /^$CHANNEL$/ AND \"pass\" = 'true') AND $timeFilter",
     "select": [
      [
       { "params": [ "ok" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "model", "operator": "=~", "value": "/^$MODEL$/" },
      { "condition": "AND", "key": "facility", "operator": "=~", "value": "/^$FACILITY$/" },
      { "condition": "AND", "key": "channel", "operator": "=~", "value": "/^$CHANNEL$/" },
      { "condition": "AND", "key": "pass", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 6 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "alias": "$col",
     "measurement": "inspection",
     "select": [
      [
       { "params": [ "ok" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "model", "operator": "=~", "value": "/^$MODEL$/" },
      { "condition": "AND", "key": "facility", "operator": "=~", "value": "/^$FACILITY$/" },
      { "condition": "AND", "key": "channel", "operator": "=~", "value": "/^$CHANNEL$/" },
      { "condition": "AND", "key": "pass", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "$MODEL",
   "type": "table",
   "gridPos": { "h": 20, "w": 10, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "inspection",
     "query": "SELECT \"ok\", \"model\", \"pass\", \"facility\", \"channel\", \"stime\", \"etime\" FROM \"inspection\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "model" ], "type": "field" }
      ],
      [
       { "params": [ "pass" ], "type": "field" }
      ],
      [
       { "params": [ "facility" ], "type": "field" }
      ],
      [
       { "params": [ "channel" ], "type": "field" }
      ],
      [
       { "params": [ "stime" ], "type": "field" }
      ],
      [
       { "params": [ "pass" ], "type": "field" },
       { "params": [ "ok" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "model", "operator": "=~", "value": "/^$MODEL$/" },
      { "condition": "AND", "key": "facility", "operator": "=~", "value": "/^$FACILITY$/" },
      { "condition": "AND", "key": "channel", "operator": "=~", "value": "/^$CHANNEL$/" }
     ]
    }
   ]
  },
  {
   "title": "Details",
   "type": "table",
   "gridPos": { "h": 20, "w": 14, "x": 10, "y": 9 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "inspection.detail",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       { "params": [ "모델" ], "type": "alias" }
      ],
      [
       { "params": [ "facility" ], "type": "field" },
       { "params": [ "검사기" ], "type": "alias" }
      ],
      [
       { "params": [ "channel" ], "type": "field" },
       { "params": [ "채널" ], "type": "alias" }
      ],
      [
       { "params": [ "iid" ], "type": "field" },
       { "params": [ "검사항목" ], "type": "alias" }
      ],
      [
       { "params": [ "min" ], "type": "field" },
       { "params": [ "MIN" ], "type": "alias" }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       { "params": [ "MAX" ], "type": "alias" }
      ],
      [
       { "params": [ "val" ], "type": "field" },
       { "params": [ "측정치" ], "type": "alias" }
      ],
      [
       { "params": [ "pass" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "model", "operator": "=~", "value": "/^$MODEL$/" },
      { "condition": "AND", "key": "facility", "operator": "=~", "value": "/^$FACILITY$/" },
      { "condition": "AND", "key": "channel", "operator": "=~", "value": "/^$CHANNEL$/" }
     ]
    }
   ]
  }
 ]
}