{
 "title": "상세 검사로그",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DATABASE", "label": "본사/지점 선택", "query": "influxdb" },
   {
    "name": "MODEL",
    "label": "모델",
    "query": "show tag values from /inspection/ with key=model"
   },
   {
    "name": "FACILITY",
    "label": "검사기",
    "query": "show tag values from /inspection/ with key=facility"
   },
   {
    "name": "CHANNEL",
    "label": "채널",
    "query": "show tag values from /inspection/ with key=channel"
   },
   { "name": "PASS", "label": "합격", "query": "true, false" },
   {
    "name": "INTERVAL",
    "label": "집계단위",
    "query": "1s, 10s, 30s, 1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "TUID", "label": "상세항목" }
  ]
 },
 "panels": [
  {
   "title": "$MODEL",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "/^inspection.summary-*/",
     "query": "SELECT \"ok\", \"model\", \"pass\", \"facility\", \"channel\", \"stime\", \"etime\" FROM \"inspection\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "model" ], "type": "field" }
      ],
      [
       { "params": [ "facility" ], "type": "field" }
      ],
      [
       { "params": [ "channel" ], "type": "field" }
      ],
      [
       { "params": [ "pass" ], "type": "field" }
      ],
      [
       { "params": [ "stime" ], "type": "field" }
      ],
      [
       { "params": [ "etime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "model", "operator": "=~", "value": "/^$MODEL$/" },
      { "condition": "AND", "key": "facility", "operator": "=~", "value": "/^$FACILITY$/" },
      { "condition": "AND", "key": "channel", "operator": "=~", "value": "/^$CHANNEL$/" },
      { "condition": "AND", "key": "pass", "operator": "=~", "value": "/^$PASS$/" },
      { "condition": "AND", "key": "tuid", "operator": "=~", "value": "/^$TUID$/" }
     ]
    }
   ]
  },
  {
   "title": "불량요소 수",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "measurement": "/^inspection.detail-*/",
     "select": [
      [
       { "params": [ "tuid" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "facility", "operator": "=~", "value": "/^$FACILITY$/" },
      { "condition": "AND", "key": "channel", "operator": "=~", "value": "/^$CHANNEL$/" },
      { "condition": "AND", "key": "model", "operator": "=~", "value": "/^$MODEL$/" },
      { "condition": "AND", "key": "tuid", "operator": "=~", "value": "/^$TUID$/" },
      { "condition": "AND", "key": "pass", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "Serial",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 22, "x": 2, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "$col",
     "measurement": "inspection.summary-20180101",
     "select": [
      [
       { "params": [ "serial" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "model", "operator": "=~", "value": "/^$MODEL$/" },
      { "condition": "AND", "key": "facility", "operator": "=~", "value": "/^$FACILITY$/" },
      { "condition": "AND", "key": "channel", "operator": "=~", "value": "/^$CHANNEL$/" },
      { "condition": "AND", "key": "tuid", "operator": "=~", "value": "/^$TUID$/" }
     ]
    }
   ]
  },
  {
   "title": "불량 요소",
   "type": "table",
   "gridPos": { "h": 11, "w": 2, "x": 0, "y": 6 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "/^inspection.detail-*/",
     "query": "SELECT \"inm\" FROM /^inspection.detail-*/ WHERE (\"model\" =~ /^$MODEL$/ AND \"facility\" =~ /^$FACILITY$/ AND \"channel\" =~ /^$CHANNEL$/ AND \"pass\" = 'false' AND \"tuid\" =~ /^$TUID$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "inm" ], "type": "field" }
      ],
      [
       { "params": [ "val" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "model", "operator": "=~", "value": "/^$MODEL$/" },
      { "condition": "AND", "key": "facility", "operator": "=~", "value": "/^$FACILITY$/" },
      { "condition": "AND", "key": "channel", "operator": "=~", "value": "/^$CHANNEL$/" },
      { "condition": "AND", "key": "pass", "operator": "=", "value": "false" },
      { "condition": "AND", "key": "tuid", "operator": "=~", "value": "/^$TUID$/" }
     ]
    }
   ]
  },
  {
   "title": "불량 요소",
   "type": "table",
   "gridPos": { "h": 11, "w": 22, "x": 2, "y": 6 },
   "targets": [
    {
     "alias": "$col",
     "measurement": "/^inspection.detail-*/",
     "query": "SELECT \"model\", \"facility\", \"channel\", \"pass\", \"min\", \"max\", \"val\" FROM /^inspection.detail-*/ WHERE (\"model\" =~ /^$MODEL$/ AND \"facility\" =~ /^$FACILITY$/ AND \"channel\" =~ /^$CHANNEL$/ AND \"pass\" =~ /^$PASS$/ AND \"tuid\" =~ /^$TUID$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "inm" ], "type": "field" }
      ],
      [
       { "params": [ "val" ], "type": "field" }
      ],
      [
       { "params": [ "pass" ], "type": "field" }
      ],
      [
       { "params": [ "min" ], "type": "field" }
      ],
      [
       { "params": [ "max" ], "type": "field" }
      ],
      [
       { "params": [ "memo" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "model", "operator": "=~", "value": "/^$MODEL$/" },
      { "condition": "AND", "key": "facility", "operator": "=~", "value": "/^$FACILITY$/" },
      { "condition": "AND", "key": "channel", "operator": "=~", "value": "/^$CHANNEL$/" },
      { "condition": "AND", "key": "tuid", "operator": "=~", "value": "/^$TUID$/" }
     ]
    }
   ]
  }
 ]
}